Script started on 2015年03月10日 (週二) 17時49分21秒
]0;F74031093@2015cpp: ~F74031093@2015cpp:~$ whoaml[Ki;pwd
F74031093
/home/F74031093
]0;F74031093@2015cpp: ~F74031093@2015cpp:~$ git config -1
error: unknown switch `1'
usage: git config [options]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    -f, --file <file>     use given config file

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 adds a new variable: name value
    --unset               removes a variable: name [value-regex]
    --unset-all           removes all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            opens an editor
    --get-color <slot>    find the color configured: [default]
    --get-colorbool <slot>
                          find the color setting: [stdout-is-tty]

Type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)

Other
    -z, --null            terminate values with NUL byte

]0;F74031093@2015cpp: ~F74031093@2015cpp:~$ git config --global user.name "chen841115"
]0;F74031093@2015cpp: ~F74031093@2015cpp:~$ git config --global user.name "chen841115"[C[1P "chen841115"[1P "chen841115"[1P "chen841115"[1P "chen841115"[1P "chen841115"[1P "chen841115"[1P "chen841115"[1P "chen841115"[1P "chen841115"m "chen841115"a "chen841115"i "chen841115"l "chen841115"[C[C[C[C[C[C[C[C[C[C[1@u[1@s[1@e[1@r[1@.[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[1P"[1P"[1P"[1P"[1P"[1P"[1P"[1P"[1P"[1P"f"7"4"0"3"1"0"9"3"@"M"A"I"L"."[1P"[1P"[1P"[1P"[1P"M"[1P"m"a"i"l"."n"c"k"u"."e"d"u"."t"w"
]0;F74031093@2015cpp: ~F74031093@2015cpp:~$ git config --global user.mail "f74031093@mail.ncku.edu.tw"[16Pname "chen841115"1[K
error: unknown switch `1'
usage: git config [options]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    -f, --file <file>     use given config file

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 adds a new variable: name value
    --unset               removes a variable: name [value-regex]
    --unset-all           removes all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            opens an editor
    --get-color <slot>    find the color configured: [default]
    --get-colorbool <slot>
                          find the color setting: [stdout-is-tty]

Type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)

Other
    -z, --null            terminate values with NUL byte

]0;F74031093@2015cpp: ~F74031093@2015cpp:~$ git clone https://github.com/<your github account>/lab1.git [A
bash: your: No such file or directory
]0;F74031093@2015cpp: ~F74031093@2015cpp:~$ git clone https://github.com/<your github account>/lab1.git [A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C

bash: your: No such file or directory
]0;F74031093@2015cpp: ~F74031093@2015cpp:~$ git clone https://github.com/chen841115/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
]0;F74031093@2015cpp: ~F74031093@2015cpp:~$ exit

Script done on 2015年03月10日 (週二) 17時52分50秒
